apiVersion: v1
kind: Service
metadata:
  name: crypto-api
  namespace: default
spec:
  selector:
    app: crypto-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
